/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import Controller.ControllerButton;
import Model.EtatPersonne;
import Observer.Observateur;
import View.Connecter;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.Int;
import java.awt.event.ActionListener;
import java.sql.*;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class VieProfessionnelle extends javax.swing.JFrame implements Observateur {

    /**
     * Creates new form VieProfess
     */
    Connecter con=new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model=new DefaultTableModel();    
    
    /**
     *
     */
    public VieProfessionnelle() {
        initComponents();
        this.setLocationRelativeTo(null);
        
      model.addColumn("id");
model.addColumn("Nom");
model.addColumn("Etat");
model.addColumn("nbPoints");

try{
stm=Connecter.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select*from personne");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Etat"),Rs.getString("nbPoints")});


}
}catch(Exception e){System.err.println(e);}
tab.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labNOM = new javax.swing.JLabel();
        labID = new javax.swing.JLabel();
        labNBPOINTS = new javax.swing.JLabel();
        labETAT = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        NBPOINT = new javax.swing.JTextField();
        NOM = new javax.swing.JTextField();
        ajouter = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        rechercher = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        Etat = new javax.swing.JComboBox<>();
        modifier = new javax.swing.JButton();
        txtETAT = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(850, 600));
        getContentPane().setLayout(null);

        labNOM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNOM.setForeground(new java.awt.Color(242, 241, 239));
        labNOM.setText("Nom :");
        getContentPane().add(labNOM);
        labNOM.setBounds(50, 130, 42, 17);

        labID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labID.setForeground(new java.awt.Color(242, 241, 239));
        labID.setText("ID :");
        getContentPane().add(labID);
        labID.setBounds(50, 100, 34, 17);

        labNBPOINTS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labNBPOINTS.setForeground(new java.awt.Color(242, 241, 239));
        labNBPOINTS.setText("Nombre de points :");
        getContentPane().add(labNBPOINTS);
        labNBPOINTS.setBounds(50, 210, 133, 17);

        labETAT.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labETAT.setForeground(new java.awt.Color(242, 241, 239));
        labETAT.setText("L'etat :");
        getContentPane().add(labETAT);
        labETAT.setBounds(50, 170, 49, 17);

        ID.setBackground(new java.awt.Color(191, 191, 191));
        ID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID);
        ID.setBounds(200, 91, 110, 30);

        NBPOINT.setBackground(new java.awt.Color(191, 191, 191));
        NBPOINT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NBPOINT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NBPOINTActionPerformed(evt);
            }
        });
        getContentPane().add(NBPOINT);
        NBPOINT.setBounds(200, 210, 110, 30);

        NOM.setBackground(new java.awt.Color(191, 191, 191));
        NOM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMActionPerformed(evt);
            }
        });
        getContentPane().add(NOM);
        NOM.setBounds(200, 130, 110, 30);

        ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/addd.jpg"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        getContentPane().add(ajouter);
        ajouter.setBounds(60, 310, 130, 40);

        supprimer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/delete.jpg"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        getContentPane().add(supprimer);
        supprimer.setBounds(200, 310, 130, 40);

        actualiser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        actualiser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/refresh.jpg"))); // NOI18N
        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });
        getContentPane().add(actualiser);
        actualiser.setBounds(60, 370, 130, 40);

        rechercher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rechercher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/search.jpg"))); // NOI18N
        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        getContentPane().add(rechercher);
        rechercher.setBounds(60, 420, 130, 40);

        jPanel1.setBackground(new java.awt.Color(108, 122, 137));

        tab.setBackground(new java.awt.Color(210, 215, 211));
        tab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tab.setForeground(new java.awt.Color(52, 73, 94));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab.setRowHeight(20);
        tab.setSelectionForeground(new java.awt.Color(52, 73, 94));
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tab);

        jPanel1.add(jScrollPane3);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(358, 110, 462, 280);

        Etat.setBackground(new java.awt.Color(191, 191, 191));
        Etat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Etat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Etudiant", "Actif", "Retraité" }));
        Etat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EtatActionPerformed(evt);
            }
        });
        getContentPane().add(Etat);
        Etat.setBounds(200, 170, 110, 30);

        modifier.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/update.jpg"))); // NOI18N
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        getContentPane().add(modifier);
        modifier.setBounds(200, 370, 130, 40);

        txtETAT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        getContentPane().add(txtETAT);
        txtETAT.setBounds(200, 420, 130, 40);

        jPanel2.setBackground(new java.awt.Color(149, 165, 166));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel1.setText("Vie Professionnelle");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 840, 80);

        jPanel3.setBackground(new java.awt.Color(108, 122, 137));
        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 80, 840, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deplace(int i){
try{
 ID.setText(model.getValueAt(i,0).toString());
 NOM.setText(model.getValueAt(i,1).toString());
 Etat.setSelectedItem(model.getValueAt(i,2).toString());
 NBPOINT.setText(model.getValueAt(i,3).toString());
    
}catch (Exception e){System.err.println(e);
JOptionPane.showMessageDialog(null,"erreur de deplacement"+e.getLocalizedMessage());}
    }
    
    private void afficher(){
try{
  model.setRowCount(0);

stm=Connecter.obtenirconnexion().createStatement();
ResultSet Rs=stm.executeQuery("Select*from personne");
while(Rs.next()){
model.addRow(new Object[]{Rs.getString("id"),Rs.getString("Nom"),Rs.getString("Etat"),Rs.getString("nbPoints")});


}
}catch(Exception e){System.err.println(e);}
tab.setModel(model);
    }
    
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
        String labID=ID.getText();
String labNOM=NOM.getText();
String labETAT=Etat.getSelectedItem().toString();
String labNBPOINTS=NBPOINT.getText();

String requete="insert into personne(ID,Nom,Etat,nbPoints)VALUES('"+labID+"','"+labNOM
+"','"+labETAT+"','"+labNBPOINTS+"')";
try{
  stm.executeUpdate(requete);
JOptionPane.showMessageDialog(null,"La personne est bien ajoutée");
NOM.setText("");
Etat.setSelectedItem(2);
NBPOINT.setText("");
   afficher();

}catch(Exception ex){JOptionPane.showMessageDialog(null,ex.getMessage());}


    }//GEN-LAST:event_ajouterActionPerformed

    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
      try{
if(JOptionPane.showConfirmDialog(null,"attention vous avez supprimer une personne,est ce que tu est sur?","supprimer personne",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION)
if(ID.getText().length()!=0){
stm.executeUpdate("Delete FROM personne where id="+ID.getText());   afficher();
}

else{JOptionPane.showMessageDialog(null,"veuillez SVP remplire le champ id !");}
}catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de supprimer \n"+e.getMessage());} 



    }//GEN-LAST:event_supprimerActionPerformed

    private void NBPOINTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NBPOINTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NBPOINTActionPerformed

    private void NOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOMActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void EtatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EtatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EtatActionPerformed

    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
      try{
 int i=tab.getSelectedRow();deplace(i);
}catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de deplacement "+e.getLocalizedMessage());}



    }//GEN-LAST:event_tabMouseClicked

    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
      afficher();
    }//GEN-LAST:event_actualiserActionPerformed

    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
      try{

 if(JOptionPane.showConfirmDialog(null,"confirmer la modification","modification",JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION) {

 stm.executeUpdate("UPDATE personne SET Nom='"+NOM.getText()+"',Etat='"+Etat.getSelectedItem().toString()+"',nbPoints='"+NBPOINT.getText()+"' WHERE id="+ID.getText());   afficher();

}
}catch(Exception e){JOptionPane.showMessageDialog(null,"erreur de modifier !!!!"+e.getMessage());
System.err.println(e);}

    }//GEN-LAST:event_modifierActionPerformed

    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed
        try{

 model.setRowCount(0);
{
Rs=stm.executeQuery("Select * FROM personne WHERE Etat='"+txtETAT.getText()+"'");
} while (Rs.next()) {
Object [] personne ={Rs.getInt(1),Rs.getString(2),Rs.getString(3),Rs.getInt(4)};
model.addRow(personne );
} if(model.getRowCount() ==0){JOptionPane.showMessageDialog(null,"il y a aucune personne");
} else { int i=0;
deplace(i);
}
} catch (Exception e){ System.err.println(e);
JOptionPane.showMessageDialog(null,e.getMessage());
}



    }//GEN-LAST:event_rechercherActionPerformed

    

	
	public String getNom() {
		   return  (NOM.getText());

	}
	public void setNom(String nom) {
		   NOM.setText(nom);
	}
        
       
 public JComboBox<String> getEtat() {
		return Etat;
	}
	 
	public JTextField getNbPoints() {
		    return NBPOINT;

        }
	public void setNbPoints(int nbPoints) {
		 NBPOINT.setText(Double.toString(nbPoints));
	}
    
        
        
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VieProfessionnelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VieProfessionnelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VieProfessionnelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VieProfessionnelle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VieProfessionnelle().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Etat;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NBPOINT;
    private javax.swing.JTextField NOM;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajouter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labETAT;
    private javax.swing.JLabel labID;
    private javax.swing.JLabel labNBPOINTS;
    private javax.swing.JLabel labNOM;
    private javax.swing.JButton modifier;
    private javax.swing.JButton rechercher;
    private javax.swing.JButton supprimer;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtETAT;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actualise() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }

    void AjouterListener(ActionListener listenForCalcButton) {
    
    }

    void SupprimerListener(ActionListener listenForCalcButton) {
    
    }
  
 void ModifierListener(ActionListener listenForCalcButton) {
    
    }    
 void RechercherListener(ActionListener listenForCalcButton) {
    
    }

 
    
     
}
